/**
 * SPDX-FileCopyrightText: Copyright (c) 2026 Ark Crew. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-Ark-Crew-NonCommercial-1.0
 *
 * ARK CREW LIMITED NON-COMMERCIAL LICENSE NOTICE
 *
 * This source code, together with its associated documentation, examples,
 * configuration files, and related materials, is collectively referred to
 * as the "Software".
 *
 * Subject to the complete terms set forth in the LICENSE file, Ark Crew
 * grants you a limited, non-exclusive, non-transferable, and non-sublicensable
 * right to access, reproduce, and modify the Software solely for personal
 * study, classroom education, academic research, and non-commercial evaluation.
 *
 * Commercial use of the Software, in whole or in part, is strictly prohibited
 * without prior written authorization from Ark Crew. Prohibited activities
 * include, without limitation, sale, sublicensing, paid distribution, use in
 * paid consulting or training, incorporation into any commercial product or
 * service, and internal development intended for commercial deployment.
 *
 * Except for the limited rights expressly granted under the applicable
 * License, no license or other right, whether express, implied, by estoppel,
 * or otherwise, is granted under any copyright, patent, trademark, trade
 * secret, mask work, or other intellectual property right belonging to
 * Ark Crew or any third party.
 *
 * Delivery or disclosure of the Software does not convey permission to use
 * the Ark Crew name, trademarks, logos, visual identity, or other branding,
 * except where strictly necessary to preserve the original attribution.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND "WITH ALL FAULTS", WITHOUT ANY
 * REPRESENTATION OR WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED,
 * STATUTORY, OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, RELIABILITY, AND
 * NON-INFRINGEMENT.
 *
 * TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ARK CREW SHALL NOT
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * PUNITIVE, OR CONSEQUENTIAL LOSS OR DAMAGE ARISING FROM OR RELATED TO
 * THE SOFTWARE, ITS USE, OR ITS INABILITY TO BE USED.
 *
 * This notice shall be retained in all authorized copies or substantial
 * portions of the Software. Removal, concealment, or unauthorized alteration
 * of this notice is prohibited.
 *
 * See the LICENSE file in the root directory of this repository for the
 * complete and controlling license terms.
 */

/* Generated by sdk_sys_config.py. Do not edit. */
#include "app_sys_config.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "ark_hal_bindings.h"
#include "iwdg.h"
#include "led.h"
#include "uart_cli.h"
#include "usb.h"
#include "usb_device.h"
#include "watchdog.h"

void *const ark_hal_adc_handles[ARK_HAL_ADC_COUNT] = {
    NULL,
    NULL,
};

void *const ark_hal_can_handles[ARK_HAL_CAN_COUNT] = {
    NULL,
};

void *const ark_hal_encoder_handles[ARK_HAL_ENCODER_COUNT] = {
    NULL,
    NULL,
};

void *const ark_hal_i2c_handles[ARK_HAL_I2C_COUNT] = {
    NULL,
    NULL,
};

void *const ark_hal_pwm_handles[ARK_HAL_PWM_COUNT] = {
    NULL,
    NULL,
    NULL,
    NULL,
};

void *const ark_hal_spi_handles[ARK_HAL_SPI_COUNT] = {
    NULL,
    NULL,
    NULL,
};

void *const ark_hal_uart_handles[ARK_HAL_UART_COUNT] = {
    NULL,
    NULL,
    NULL,
};

const uint32_t ark_hal_pwm_channels[ARK_HAL_PWM_COUNT] = {
    0U,
    0U,
    0U,
    0U,
};

void *const ark_hal_watchdog_handle = &hiwdg;

#if defined(ARK_USB_DEVICE_CUBEMX_INIT)
extern USBD_HandleTypeDef hUsbDeviceFS;
#endif
void *const ark_hal_usb_device_handle = &hUsbDeviceFS;

const ark_hal_soft_i2c_config_t ark_hal_soft_i2c_configs[ARK_HAL_SOFT_I2C_COUNT] = {
    {
        .scl = { .port = ARK_HAL_GPIO_PORT_A, .pin = ARK_HAL_GPIO_PIN(0U), .active_level = 1U },
        .sda = { .port = ARK_HAL_GPIO_PORT_A, .pin = ARK_HAL_GPIO_PIN(0U), .active_level = 1U },
        .delay_us = 0U,
        .deinit_hardware_i2c = false,
        .hardware_i2c_id = ARK_HAL_I2C_1,
    },
};

static const led_instance_config_t ark_led_instances[] = {
    {
        .id = 0U,
        .gpio = { .port = ARK_HAL_GPIO_PORT_C, .pin = ARK_HAL_GPIO_PIN(13U), .active_level = 0U },
    },
};

const led_config_t ark_led_config = {
    .instances = ark_led_instances,
    .count = sizeof(ark_led_instances) / sizeof(ark_led_instances[0]),
};

const usb_config_t ark_usb_config = {
    .stream_name = "debug",
};

static const uint8_t ark_uart_cli_welcome[] =
    "\r\n================================\r\n"
    " Welcome to ARK CREW Embedded CLI\r\n"
    " Stream: debug\r\n"
    " Arrow keys edit/history; type 'help'\r\n"
    "================================\r\n";

const uart_cli_config_t ark_uart_cli_config = {
    .stream_name = "debug",
    .welcome = ark_uart_cli_welcome,
    .welcome_size = sizeof(ark_uart_cli_welcome) - 1U,
};

