/**
 * SPDX-FileCopyrightText: Copyright (c) 2026 Ark Crew. All rights reserved.
 * SPDX-License-Identifier: LicenseRef-Ark-Crew-NonCommercial-1.0
 *
 * ARK CREW LIMITED NON-COMMERCIAL LICENSE NOTICE
 *
 * This source code, together with its associated documentation, examples,
 * configuration files, and related materials, is collectively referred to
 * as the "Software".
 *
 * Subject to the complete terms set forth in the LICENSE file, Ark Crew
 * grants you a limited, non-exclusive, non-transferable, and non-sublicensable
 * right to access, reproduce, and modify the Software solely for personal
 * study, classroom education, academic research, and non-commercial evaluation.
 *
 * Commercial use of the Software, in whole or in part, is strictly prohibited
 * without prior written authorization from Ark Crew. Prohibited activities
 * include, without limitation, sale, sublicensing, paid distribution, use in
 * paid consulting or training, incorporation into any commercial product or
 * service, and internal development intended for commercial deployment.
 *
 * Except for the limited rights expressly granted under the applicable
 * License, no license or other right, whether express, implied, by estoppel,
 * or otherwise, is granted under any copyright, patent, trademark, trade
 * secret, mask work, or other intellectual property right belonging to
 * Ark Crew or any third party.
 *
 * Delivery or disclosure of the Software does not convey permission to use
 * the Ark Crew name, trademarks, logos, visual identity, or other branding,
 * except where strictly necessary to preserve the original attribution.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND "WITH ALL FAULTS", WITHOUT ANY
 * REPRESENTATION OR WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED,
 * STATUTORY, OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, RELIABILITY, AND
 * NON-INFRINGEMENT.
 *
 * TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ARK CREW SHALL NOT
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * PUNITIVE, OR CONSEQUENTIAL LOSS OR DAMAGE ARISING FROM OR RELATED TO
 * THE SOFTWARE, ITS USE, OR ITS INABILITY TO BE USED.
 *
 * This notice shall be retained in all authorized copies or substantial
 * portions of the Software. Removal, concealment, or unauthorized alteration
 * of this notice is prohibited.
 *
 * See the LICENSE file in the root directory of this repository for the
 * complete and controlling license terms.
 */
/* Generated by ark_dts.py. Do not edit. */
#include "ark_dts_generated.h"

#include <stddef.h>
#include <stdint.h>
#include "ark_dts.h"
#include "ark_hal_bindings.h"
#include "ark_net.h"
#include "dht11.h"
#include "iwdg.h"
#include "json.h"
#include "lcd.h"
#include "led.h"
#include "spi.h"
#include "stream.h"
#include "uart_cli.h"
#include "usart.h"
#include "watchdog.h"
#include "wifi.h"
#include "wifi_esp_at.h"

void *const ark_hal_adc_handles[2] = {
    NULL,
    NULL,
};

void *const ark_hal_can_handles[1] = {
    NULL,
};

void *const ark_hal_encoder_handles[2] = {
    NULL,
    NULL,
};

void *const ark_hal_i2c_handles[2] = {
    NULL,
    NULL,
};

void *const ark_hal_pwm_handles[4] = {
    NULL,
    NULL,
    NULL,
    NULL,
};

void *const ark_hal_spi_handles[3] = {
    &hspi1,
    NULL,
    NULL,
};

void *const ark_hal_uart_handles[3] = {
    &huart1,
    NULL,
    &huart3,
};

void *const ark_hal_watchdog_handle = &hiwdg;
void *const ark_hal_usb_device_handle = NULL;

const uint32_t ark_hal_pwm_channels[4] = {
    0U,
    0U,
    0U,
    0U,
};

const ark_hal_soft_i2c_config_t ark_hal_soft_i2c_configs[1] = {{
    .scl = {.port = ARK_HAL_GPIO_PORT_A, .pin = 0U, .active_level = 0U},
    .sda = {.port = ARK_HAL_GPIO_PORT_A, .pin = 0U, .active_level = 0U},
    .delay_us = 0U,
    .deinit_hardware_i2c = false, .hardware_i2c_id = ARK_HAL_I2C_1,
}};

static const uint8_t ark_dts_data[] = {
    0x41U, 0x52U, 0x4BU, 0x20U, 0x43U, 0x52U, 0x45U, 0x57U, 0x20U, 0x41U, 0x52U, 0x4BU,
    0x20U, 0x4EU, 0x65U, 0x74U, 0x77U, 0x6FU, 0x72U, 0x6BU, 0x20U, 0x44U, 0x65U, 0x6DU,
    0x6FU, 0x00U, 0x63U, 0x38U, 0x74U, 0x36U, 0x5FU, 0x61U, 0x72U, 0x6BU, 0x5FU, 0x6EU,
    0x65U, 0x74U, 0x00U, 0x73U, 0x74U, 0x6DU, 0x33U, 0x32U, 0x66U, 0x31U, 0x30U, 0x33U,
    0x63U, 0x38U, 0x00U, 0x73U, 0x69U, 0x6DU, 0x70U, 0x6CU, 0x65U, 0x2DU, 0x62U, 0x75U,
    0x73U, 0x00U, 0x01U, 0x00U, 0x00U, 0x00U, 0x61U, 0x72U, 0x6BU, 0x5FU, 0x68U, 0x61U,
    0x6CU, 0x5FU, 0x67U, 0x70U, 0x69U, 0x6FU, 0x00U, 0x00U, 0x08U, 0x01U, 0x40U, 0x00U,
    0x04U, 0x00U, 0x00U, 0x02U, 0x00U, 0x00U, 0x00U, 0x00U, 0x0CU, 0x01U, 0x40U, 0x00U,
    0x04U, 0x00U, 0x00U, 0x00U, 0x10U, 0x01U, 0x40U, 0x00U, 0x04U, 0x00U, 0x00U, 0x61U,
    0x72U, 0x6BU, 0x5FU, 0x68U, 0x61U, 0x6CU, 0x5FU, 0x77U, 0x61U, 0x74U, 0x63U, 0x68U,
    0x64U, 0x6FU, 0x67U, 0x00U, 0x77U, 0x61U, 0x74U, 0x63U, 0x68U, 0x64U, 0x6FU, 0x67U,
    0x00U, 0x61U, 0x72U, 0x6BU, 0x5FU, 0x68U, 0x61U, 0x6CU, 0x5FU, 0x73U, 0x70U, 0x69U,
    0x00U, 0x00U, 0x30U, 0x01U, 0x40U, 0x00U, 0x04U, 0x00U, 0x00U, 0x6CU, 0x63U, 0x64U,
    0x00U, 0x01U, 0x00U, 0x00U, 0x00U, 0x01U, 0x00U, 0x00U, 0x00U, 0x01U, 0x00U, 0x00U,
    0x00U, 0x01U, 0x00U, 0x00U, 0x00U, 0x02U, 0x00U, 0x00U, 0x00U, 0x01U, 0x00U, 0x00U,
    0x00U, 0x01U, 0x00U, 0x00U, 0x00U, 0x03U, 0x00U, 0x00U, 0x00U, 0x01U, 0x00U, 0x00U,
    0x00U, 0x01U, 0x00U, 0x00U, 0x00U, 0x04U, 0x00U, 0x00U, 0x00U, 0x01U, 0x00U, 0x00U,
    0x00U, 0x61U, 0x72U, 0x6BU, 0x5FU, 0x68U, 0x61U, 0x6CU, 0x5FU, 0x75U, 0x61U, 0x72U,
    0x74U, 0x00U, 0x00U, 0x38U, 0x01U, 0x40U, 0x00U, 0x04U, 0x00U, 0x00U, 0x00U, 0x10U,
    0x0EU, 0x00U, 0x73U, 0x74U, 0x72U, 0x65U, 0x61U, 0x6DU, 0x00U, 0x63U, 0x6CU, 0x69U,
    0x00U, 0x75U, 0x61U, 0x72U, 0x74U, 0x5FU, 0x63U, 0x6CU, 0x69U, 0x00U, 0x41U, 0x52U,
    0x4BU, 0x20U, 0x43U, 0x52U, 0x45U, 0x57U, 0x20U, 0x41U, 0x52U, 0x4BU, 0x20U, 0x4EU,
    0x45U, 0x54U, 0x20U, 0x72U, 0x65U, 0x61U, 0x64U, 0x79U, 0x00U, 0x00U, 0x48U, 0x00U,
    0x40U, 0x00U, 0x04U, 0x00U, 0x00U, 0x00U, 0xC2U, 0x01U, 0x00U, 0x65U, 0x73U, 0x70U,
    0x30U, 0x31U, 0x00U, 0x69U, 0x6EU, 0x74U, 0x65U, 0x72U, 0x72U, 0x75U, 0x70U, 0x74U,
    0x00U, 0x77U, 0x69U, 0x66U, 0x69U, 0x00U, 0x77U, 0x69U, 0x66U, 0x69U, 0x5FU, 0x65U,
    0x73U, 0x70U, 0x5FU, 0x61U, 0x74U, 0x00U, 0x59U, 0x4FU, 0x55U, 0x52U, 0x5FU, 0x57U,
    0x49U, 0x46U, 0x49U, 0x5FU, 0x53U, 0x53U, 0x49U, 0x44U, 0x00U, 0x43U, 0x48U, 0x41U,
    0x4EU, 0x47U, 0x45U, 0x5FU, 0x4DU, 0x45U, 0x5FU, 0x57U, 0x49U, 0x46U, 0x49U, 0x5FU,
    0x50U, 0x41U, 0x53U, 0x53U, 0x57U, 0x4FU, 0x52U, 0x44U, 0x00U, 0x6CU, 0x65U, 0x64U,
    0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x03U, 0x00U, 0x00U, 0x00U, 0x0DU, 0x00U, 0x00U,
    0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x64U, 0x68U, 0x74U, 0x31U, 0x31U, 0x00U, 0x02U,
    0x00U, 0x00U, 0x00U, 0x05U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x6AU,
    0x73U, 0x6FU, 0x6EU, 0x00U, 0x61U, 0x72U, 0x6BU, 0x5FU, 0x6EU, 0x65U, 0x74U, 0x00U,
    0x31U, 0x35U, 0x34U, 0x2EU, 0x32U, 0x30U, 0x32U, 0x2EU, 0x31U, 0x31U, 0x39U, 0x2EU,
    0x31U, 0x34U, 0x35U, 0x00U, 0x28U, 0x23U, 0x00U, 0x00U, 0x63U, 0x38U, 0x74U, 0x36U,
    0x2DU, 0x61U, 0x72U, 0x6BU, 0x2DU, 0x6EU, 0x65U, 0x74U, 0x2DU, 0x30U, 0x31U, 0x00U,
    0x43U, 0x48U, 0x41U, 0x4EU, 0x47U, 0x45U, 0x5FU, 0x4DU, 0x45U, 0x5FU, 0x44U, 0x45U,
    0x56U, 0x49U, 0x43U, 0x45U, 0x5FU, 0x50U, 0x41U, 0x53U, 0x53U, 0x57U, 0x4FU, 0x52U,
    0x44U, 0x00U, 0x88U, 0x13U, 0x00U, 0x00U, 0xD0U, 0x07U, 0x00U, 0x00U, 0x40U, 0x1FU,
    0x00U, 0x00U, 0xF4U, 0x01U, 0x00U, 0x00U,
};

static const ark_of_property_t ark_dts_properties[] = {
    {54993U, 0U, 26U, ARK_OF_PROP_STRING},
    {10916U, 26U, 25U, ARK_OF_PROP_STRING},
    {10916U, 51U, 11U, ARK_OF_PROP_STRING},
    {52956U, 62U, 4U, ARK_OF_PROP_U32},
    {19181U, 62U, 4U, ARK_OF_PROP_U32},
    {26644U, 66U, 0U, ARK_OF_PROP_BOOL},
    {10916U, 66U, 13U, ARK_OF_PROP_STRING},
    {50785U, 79U, 8U, ARK_OF_PROP_U32},
    {22506U, 66U, 0U, ARK_OF_PROP_BOOL},
    {43040U, 87U, 4U, ARK_OF_PROP_U32},
    {10916U, 66U, 13U, ARK_OF_PROP_STRING},
    {50785U, 91U, 8U, ARK_OF_PROP_U32},
    {22506U, 66U, 0U, ARK_OF_PROP_BOOL},
    {43040U, 87U, 4U, ARK_OF_PROP_U32},
    {10916U, 66U, 13U, ARK_OF_PROP_STRING},
    {50785U, 99U, 8U, ARK_OF_PROP_U32},
    {22506U, 66U, 0U, ARK_OF_PROP_BOOL},
    {43040U, 87U, 4U, ARK_OF_PROP_U32},
    {10916U, 107U, 17U, ARK_OF_PROP_STRING},
    {10916U, 124U, 9U, ARK_OF_PROP_STRING},
    {10916U, 133U, 12U, ARK_OF_PROP_STRING},
    {50785U, 145U, 8U, ARK_OF_PROP_U32},
    {10916U, 153U, 4U, ARK_OF_PROP_STRING},
    {54065U, 157U, 12U, ARK_OF_PROP_U32},
    {21394U, 169U, 12U, ARK_OF_PROP_U32},
    {6624U, 181U, 12U, ARK_OF_PROP_U32},
    {59323U, 193U, 12U, ARK_OF_PROP_U32},
    {10916U, 205U, 13U, ARK_OF_PROP_STRING},
    {50785U, 218U, 8U, ARK_OF_PROP_U32},
    {34022U, 226U, 4U, ARK_OF_PROP_U32},
    {10916U, 230U, 7U, ARK_OF_PROP_STRING},
    {28073U, 237U, 4U, ARK_OF_PROP_STRING},
    {34022U, 226U, 4U, ARK_OF_PROP_U32},
    {10916U, 241U, 9U, ARK_OF_PROP_STRING},
    {28073U, 237U, 4U, ARK_OF_PROP_STRING},
    {61339U, 250U, 23U, ARK_OF_PROP_STRING},
    {10916U, 205U, 13U, ARK_OF_PROP_STRING},
    {50785U, 273U, 8U, ARK_OF_PROP_U32},
    {34022U, 281U, 4U, ARK_OF_PROP_U32},
    {10916U, 230U, 7U, ARK_OF_PROP_STRING},
    {28073U, 285U, 6U, ARK_OF_PROP_STRING},
    {50596U, 291U, 10U, ARK_OF_PROP_STRING},
    {10916U, 301U, 5U, ARK_OF_PROP_STRING},
    {10916U, 306U, 12U, ARK_OF_PROP_STRING},
    {28073U, 285U, 6U, ARK_OF_PROP_STRING},
    {34022U, 281U, 4U, ARK_OF_PROP_U32},
    {37795U, 318U, 15U, ARK_OF_PROP_STRING},
    {63385U, 333U, 24U, ARK_OF_PROP_STRING},
    {12936U, 66U, 0U, ARK_OF_PROP_BOOL},
    {10916U, 357U, 4U, ARK_OF_PROP_STRING},
    {50785U, 361U, 4U, ARK_OF_PROP_U32},
    {24041U, 365U, 12U, ARK_OF_PROP_U32},
    {10916U, 377U, 6U, ARK_OF_PROP_STRING},
    {38559U, 383U, 12U, ARK_OF_PROP_U32},
    {10916U, 395U, 5U, ARK_OF_PROP_STRING},
    {10916U, 400U, 8U, ARK_OF_PROP_STRING},
    {174U, 408U, 16U, ARK_OF_PROP_STRING},
    {55828U, 424U, 4U, ARK_OF_PROP_U32},
    {28393U, 428U, 16U, ARK_OF_PROP_STRING},
    {55363U, 444U, 26U, ARK_OF_PROP_STRING},
    {26776U, 470U, 4U, ARK_OF_PROP_U32},
    {8633U, 474U, 4U, ARK_OF_PROP_U32},
    {4151U, 478U, 4U, ARK_OF_PROP_U32},
    {19247U, 482U, 4U, ARK_OF_PROP_U32},
};

static const ark_of_node_t ark_dts_nodes[] = {
    {48466U, 255U, 1U, 255U, 0U, 2U, 0U},
    {54967U, 0U, 2U, 21U, 2U, 4U, 0U},
    {57068U, 1U, 255U, 3U, 6U, 4U, 1U},
    {56665U, 1U, 255U, 4U, 10U, 4U, 2U},
    {56266U, 1U, 255U, 5U, 14U, 4U, 3U},
    {29392U, 1U, 255U, 6U, 18U, 1U, 4U},
    {65182U, 1U, 255U, 7U, 19U, 1U, 0U},
    {13681U, 1U, 8U, 9U, 20U, 2U, 5U},
    {62997U, 7U, 255U, 255U, 22U, 5U, 0U},
    {24329U, 1U, 10U, 12U, 27U, 3U, 6U},
    {52786U, 9U, 255U, 11U, 30U, 3U, 0U},
    {22904U, 9U, 255U, 255U, 33U, 3U, 0U},
    {22627U, 1U, 13U, 16U, 36U, 3U, 7U},
    {3935U, 12U, 14U, 255U, 39U, 3U, 8U},
    {9321U, 13U, 15U, 255U, 42U, 1U, 0U},
    {19725U, 14U, 255U, 255U, 43U, 6U, 0U},
    {36850U, 1U, 17U, 18U, 49U, 1U, 0U},
    {14152U, 16U, 255U, 255U, 50U, 2U, 0U},
    {50317U, 1U, 255U, 19U, 52U, 2U, 0U},
    {22176U, 1U, 255U, 20U, 54U, 1U, 0U},
    {3007U, 1U, 255U, 255U, 55U, 8U, 0U},
    {51211U, 0U, 22U, 255U, 63U, 0U, 0U},
    {4459U, 21U, 255U, 255U, 63U, 1U, 0U},
};

static const ark_of_hal_ref_t ark_dts_hal_refs[] = {
    {2U, ARK_OF_HAL_GPIO, 0U},
    {3U, ARK_OF_HAL_GPIO, 1U},
    {4U, ARK_OF_HAL_GPIO, 2U},
    {7U, ARK_OF_HAL_SPI, 0U},
    {9U, ARK_OF_HAL_UART, 0U},
    {12U, ARK_OF_HAL_UART, 2U},
};

const ark_of_blob_t ark_of_blob = {
    ark_dts_nodes, sizeof(ark_dts_nodes) / sizeof(ark_dts_nodes[0]),
    ark_dts_properties, sizeof(ark_dts_properties) / sizeof(ark_dts_properties[0]),
    ark_dts_data,
    ark_dts_hal_refs, sizeof(ark_dts_hal_refs) / sizeof(ark_dts_hal_refs[0]),
};

bool ark_dts_register_components(void)
{
    bool ok = true;
    ok = watchdog_register() && ok;
    ok = lcd_register() && ok;
    ok = stream_register() && ok;
    ok = uart_cli_register() && ok;
    ok = wifi_register() && ok;
    ok = wifi_esp_at_register() && ok;
    ok = led_register() && ok;
    ok = dht11_register() && ok;
    ok = json_register() && ok;
    ok = ark_net_register() && ok;
    return ok;
}
